title: Strata by HTML5 UP
description: "**I am Strata**, a super simple\nresponsive site template freebie\ncrafted by [HTML5 UP](http://html5up.net)."
copyright: Untitled
sass:
  sass_dir: assets/sass
url: https://easybikepark.com/
github:
  url: https://easybikepark.com/
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5

#collections_dir: _collections
collections:
  bikeparks:
    output: true
    permalink: /:collection/:path/


str_price: Prezzo
str_currency: euro